### ISSUE TITLE
gitignore usage

### ISSUE THREAD

**Issue by coherent17** [CharLie071005/OOP_final_project#5]
check how to use gitignore
don't push cppcheck into the repo!

**Comment by Ouzheee** [comment]
Got it !

**Comment by coherent17** [comment]
gitignore, should ignore the whole folder, not just part of the files inside the cppcheck folder.

**Comment by Ouzheee** [comment]
Is is incorrect?
It seems like the cppcheck doesn't push to repo anymore.
```git
third-party/*
*.jpg
*.png
obj/*.o
obj/*.d
Image_Processing
cppchecnk-2.13.0
```

**Comment by coherent17** [comment]
should be:

```bash
cppchecnk-2.13.0/
```
To ignore an entire directory with all its contents, you need to include the name of the directory with the slash / at the end!

Besides, you also push the cppcheck compressed file, should be deleted...
